services:
    redis:
        image: redis
        container_name: redis-server
        volumes:
            - redis_data:/data

    api:
        build: .
        env_file:
            - .env
        container_name: documind-api
        ports:
            - "8000:8000"
        depends_on:
            - redis
        volumes:
            - rag_storage:/app/storage
            - pdf_storage:/app/uploaded_pdfs

volumes:
    redis_data:
    rag_storage:
    pdf_storage: