services:
    redis:
        image: redis
        container_name: redis-server

    api:
        build: .
        env_file:
            - .env
        container_name: documind-api
        ports:
            - "8000:8000"
        depends_on: 
            - redis